blank_issues_enabled: true
contact_links:
  - name: I need help setting up or troubleshooting
    url: https://github.com/TheAcharya/MarkerData/discussions
    about: Questions not answered in the documentation, discussions forum, or example projects.
