name: Feature Request
description: Suggest an idea for Marker Data
title: "Feature Request: "
labels: ["feature request"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and detailed description of the feature request here.
      placeholder: "Enter the detailed description here"
    validations:
      required: true
