name: Feature Request
description: Suggest an idea for Marker Data
title: ""
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        ### Feature Request
        A clear and detailed description of the feature request here.
