name: Feature Request
description: Suggest an idea for Marker Data
title: " "
labels: "feature request"
body:
- type: textarea
  attributes:
    label: Feature Request
    description: A clear and detail description of the feature request here.
  validations:
    required: true