name: build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'           # .md files anywhere in the repo
      - '**/LICENSE'        # LICENSE files anywhere in the repo
      - '**/.gitignore'     # .gitignore files anywhere in the repo
      - '**/*.png'          # .png image files anywhere in the repo
      - '**/*.pdf'          # .pdf files anywhere in the repo
      - '**/*.cursorrules'  # .cursorrules files anywhere in the repo
      - '**/*.xml'          # .xml files anywhere in the repo
      
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'           # .md files anywhere in the repo
      - '**/LICENSE'        # LICENSE files anywhere in the repo
      - '**/.gitignore'     # .gitignore files anywhere in the repo
      - '**/*.png'          # .png image files anywhere in the repo
      - '**/*.pdf'          # .pdf files anywhere in the repo
      - '**/*.cursorrules'  # .cursorrules files anywhere in the repo
      - '**/*.xml'          # .xml files anywhere in the repo
      
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Xcode Installations
      run: sudo ls -1 /Applications | grep "Xcode"
      
    - name: Select Xcode 26
      run: sudo xcode-select -s /Applications/Xcode_26.0.0.app/Contents/Developer
    
    - name: Change to Project Directory
      run: cd Source/Marker\ Data

    - name: Prepare Directories
      run: |
        PARENT=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
        mkdir -p "$PARENT/dist/dmg-builds/app-build"
        mkdir -p "$PARENT/dist/dmg-builds/sdk"
        
    - name: Copy Workflow Extensions SDK
      run: |
        mkdir -p dist/dmg-builds/sdk
        cp -R ./SDK/Workflow_Extensions_1.0.3.dmg ./dist/dmg-builds/sdk
        
    - name: Mount Workflow Extensions DMG
      run: |
        hdiutil attach ./dist/dmg-builds/sdk/Workflow_Extensions_1.0.3.dmg
    
    - name: Install Workflow Extensions SDK
      run: |
        sudo installer -pkg /Volumes/WorkflowExtensionsSDK/WorkflowExtensionsSDK.pkg -target /
    
    - name: View Volume Directory
      run: |
        ls /Volumes

    - name: View Workflow Extensions SDK DMG Directory
      run: |
        ls /Volumes/WorkflowExtensionsSDK

    - name: Unmount Workflow Extensions SDK DMG
      run: |
        hdiutil detach /Volumes/WorkflowExtensionsSDK

    - name: Check Installed Workflow Extensions SDK Directory
      run: |
        ls /Library/Developer/SDKs

    - name: Build Marker Data
      run: |
        PARENT=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
        PROJECT_PATH="Source/Marker Data/Marker Data.xcodeproj"
        SCHEME="Marker Data"
        CONFIGURATION="Release"
        DESTINATION="platform=macOS,arch=arm64"
        BUILD_FOLDER="$PARENT/dist/dmg-builds/app-build"
        
        xcodebuild -project "$PROJECT_PATH" -scheme "$SCHEME" -configuration "$CONFIGURATION" -destination "$DESTINATION" -derivedDataPath "$BUILD_FOLDER" clean build ONLY_ACTIVE_ARCH=NO EXCLUDED_ARCHS="x86_64" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -allowProvisioningUpdates | grep -v "Workflow Extension isn't code signed but requires entitlements" | grep -v "Marker Data isn't code signed but requires entitlements" | xcbeautify && exit ${PIPESTATUS[0]}
