name: test_build_2

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create Test Build'
        required: true
        default: 'no'

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Xcode installations
      run: sudo ls -1 /Applications | grep "Xcode"
      
    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Change to Xcode Project Directory
      run: cd Source/Marker\ Data

    - name: Prepare Directories
      run: |
        PARENT=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
        mkdir -p "$PARENT/dist/dmg-builds/latest-build"
        mkdir -p "$PARENT/dist/dmg-builds/app-build"
        mkdir -p "$PARENT/dist/dmg-builds/sdk"
        
    - name: Copy Local Distribution 
      run: |
        mkdir -p dist/dmg-builds
        mkdir -p dist/dmg-builds/latest-build
        cp -R ./Distribution/dmg-builds/. ./dist/dmg-builds

    - name: Verify Copied Files
      run: |
        echo "Checking copied files..."
        ls -l ./dist/dmg-builds
        ls -l ./dist/dmg-builds/latest-build
        ls -l ./dist/dmg-builds/uninstaller/include
        
    - name: Copy Workflow Extensions SDK
      run: |
        mkdir -p dist/dmg-builds/sdk
        cp -R ./SDK/Workflow_Extensions_1.0.2.dmg ./dist/dmg-builds/sdk
        
    - name: Mount Workflow Extensions DMG
      run: |
        hdiutil attach ./dist/dmg-builds/sdk/Workflow_Extensions_1.0.2.dmg
    
    - name: Install Workflow Extensions SDK
      run: |
        sudo installer -pkg /Volumes/WorkflowExtensionsSDK/WorkflowExtensionsSDK.pkg -target /
    
    - name: View Volume Directory
      run: |
        ls /Volumes

    - name: View Workflow Extensions SDK DMG Directory
      run: |
        ls /Volumes/WorkflowExtensionsSDK

    - name: Unmount Workflow Extensions SDK DMG
      run: |
        hdiutil detach /Volumes/WorkflowExtensionsSDK

    - name: Check Installed Workflow Extensions SDK Directory
      run: |
        ls /Library/Developer/SDKs

    - name: Build Marker Data
      env: 
        APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
        APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
        KEYCHAIN_PASSWORD_M: ${{ secrets.KEYCHAIN_PASSWORD_M }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        PARENT=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
        PROJECT_PATH="Source/Marker Data/Marker Data.xcodeproj"
        SCHEME="Marker Data"
        CONFIGURATION="Release"
        DESTINATION="platform=macOS"
        BUILD_FOLDER="$PARENT/dist/dmg-builds/app-build"
        echo "PARENT=$PARENT" >> $GITHUB_ENV
        echo "CONFIG=$CONFIGURATION" >> $GITHUB_ENV
        
        echo $APPLE_CERT_DATA | base64 --decode > certificate.p12
        security create-keychain -p $KEYCHAIN_PASSWORD_M build-m.keychain
        security default-keychain -s build-m.keychain
        security unlock-keychain -p $KEYCHAIN_PASSWORD_M build-m.keychain
        security import certificate.p12 -k build-m.keychain -P $APPLE_CERT_PASSWORD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,xcodebuild: -s -k $KEYCHAIN_PASSWORD_M build-m.keychain

        xcodebuild -project "$PROJECT_PATH" -scheme "$SCHEME" -configuration "$CONFIGURATION" -destination "$DESTINATION" -derivedDataPath "$BUILD_FOLDER" clean build | xcpretty
        
    