name: update_pagemaker

on:
  workflow_dispatch:

jobs:
  update_pagemaker:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release info
        id: get_release
        run: |
            latest_release_tag=$(curl -sSL https://api.github.com/repos/TheAcharya/MarkerData-Pagemaker/releases/latest | jq -r '.tag_name | ltrimstr("v")')
            latest_release_url=$(curl -sSL https://api.github.com/repos/TheAcharya/MarkerData-Pagemaker/releases/latest | jq -r '.assets[] | select(.name | contains("Source code")) | .browser_download_url')
            
            echo "Latest release tag: $latest_release_tag"
            echo "Latest release URL: $latest_release_url"
            
            echo "TAG=$latest_release_tag" >> $GITHUB_ENV
            echo "URL=$latest_release_url" >> $GITHUB_ENV

      - name: Download and extract latest release
        run: |
            curl -L -o pagemaker_source.zip "${{ env.URL }}"
            
            # Create temp directory and extract
            mkdir -p temp_extract
            unzip -q pagemaker_source.zip -d temp_extract
            
            # Find the main directory in the extracted content
            extract_dir=$(find temp_extract -type d -depth 1 | head -n 1)
            
            # Copy the Pagemaker.html file to destination
            cp "$extract_dir/Pagemaker.html" "./Source/Marker Data/Marker Data/Resources/Pagemaker.html"
            
            echo "Copied Pagemaker.html from version ${{ env.TAG }}"
            
            # Clean up
            rm -rf temp_extract pagemaker_source.zip

      - name: Commit and push changes
        run: |
            git status
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add "./Source/Marker Data/Marker Data/Resources/Pagemaker.html"
            git commit -m "Updated Pagemaker Version ${{ env.TAG }}"
            git push